package com.tisco.lkmes.mme.entity;

public class MeasureSite {

	/** 序列主键. */
	private Long sid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column LKMES2.MES_MME_MEASURE_SITE.METER_NAME
	 * 
	 * @ibatorgenerated Sat Oct 12 16:56:56 CST 2013
	 */
	private String meterName;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column LKMES2.MES_MME_MEASURE_SITE.IP
	 * 
	 * @ibatorgenerated Sat Oct 12 16:56:56 CST 2013
	 */
	private String ip;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column LKMES2.MES_MME_MEASURE_SITE.SITE_NO
	 * 
	 * @ibatorgenerated Sat Oct 12 16:56:56 CST 2013
	 */
	private String siteNo;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column LKMES2.MES_MME_MEASURE_SITE.SITE_NAME
	 * 
	 * @ibatorgenerated Sat Oct 12 16:56:56 CST 2013
	 */
	private String siteName;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column LKMES2.MES_MME_MEASURE_SITE.SITE_TYPE
	 * 
	 * @ibatorgenerated Sat Oct 12 16:56:56 CST 2013
	 */
	private String siteType;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column LKMES2.MES_MME_MEASURE_SITE.ZERO_STANDARD
	 * 
	 * @ibatorgenerated Sat Oct 12 16:56:56 CST 2013
	 */
	private String zeroStandard;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column LKMES2.MES_MME_MEASURE_SITE.COM_PORT
	 * 
	 * @ibatorgenerated Sat Oct 12 16:56:56 CST 2013
	 */
	private String comPort;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column LKMES2.MES_MME_MEASURE_SITE.COM_FREQUENCY
	 * 
	 * @ibatorgenerated Sat Oct 12 16:56:56 CST 2013
	 */
	private Integer comFrequency;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column LKMES2.MES_MME_MEASURE_SITE.METER_NAME
	 * 
	 * @return the value of LKMES2.MES_MME_MEASURE_SITE.METER_NAME
	 * 
	 * @ibatorgenerated Sat Oct 12 16:56:56 CST 2013
	 */
	public String getMeterName() {
		return meterName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column LKMES2.MES_MME_MEASURE_SITE.METER_NAME
	 * 
	 * @param meterName
	 *          the value for LKMES2.MES_MME_MEASURE_SITE.METER_NAME
	 * 
	 * @ibatorgenerated Sat Oct 12 16:56:56 CST 2013
	 */
	public void setMeterName(String meterName) {
		this.meterName = meterName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column LKMES2.MES_MME_MEASURE_SITE.IP
	 * 
	 * @return the value of LKMES2.MES_MME_MEASURE_SITE.IP
	 * 
	 * @ibatorgenerated Sat Oct 12 16:56:56 CST 2013
	 */
	public String getIp() {
		return ip;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column LKMES2.MES_MME_MEASURE_SITE.IP
	 * 
	 * @param ip
	 *          the value for LKMES2.MES_MME_MEASURE_SITE.IP
	 * 
	 * @ibatorgenerated Sat Oct 12 16:56:56 CST 2013
	 */
	public void setIp(String ip) {
		this.ip = ip;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column LKMES2.MES_MME_MEASURE_SITE.SITE_NO
	 * 
	 * @return the value of LKMES2.MES_MME_MEASURE_SITE.SITE_NO
	 * 
	 * @ibatorgenerated Sat Oct 12 16:56:56 CST 2013
	 */
	public String getSiteNo() {
		return siteNo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column LKMES2.MES_MME_MEASURE_SITE.SITE_NO
	 * 
	 * @param siteNo
	 *          the value for LKMES2.MES_MME_MEASURE_SITE.SITE_NO
	 * 
	 * @ibatorgenerated Sat Oct 12 16:56:56 CST 2013
	 */
	public void setSiteNo(String siteNo) {
		this.siteNo = siteNo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column LKMES2.MES_MME_MEASURE_SITE.SITE_NAME
	 * 
	 * @return the value of LKMES2.MES_MME_MEASURE_SITE.SITE_NAME
	 * 
	 * @ibatorgenerated Sat Oct 12 16:56:56 CST 2013
	 */
	public String getSiteName() {
		return siteName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column LKMES2.MES_MME_MEASURE_SITE.SITE_NAME
	 * 
	 * @param siteName
	 *          the value for LKMES2.MES_MME_MEASURE_SITE.SITE_NAME
	 * 
	 * @ibatorgenerated Sat Oct 12 16:56:56 CST 2013
	 */
	public void setSiteName(String siteName) {
		this.siteName = siteName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column LKMES2.MES_MME_MEASURE_SITE.SITE_TYPE
	 * 
	 * @return the value of LKMES2.MES_MME_MEASURE_SITE.SITE_TYPE
	 * 
	 * @ibatorgenerated Sat Oct 12 16:56:56 CST 2013
	 */
	public String getSiteType() {
		return siteType;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column LKMES2.MES_MME_MEASURE_SITE.SITE_TYPE
	 * 
	 * @param siteType
	 *          the value for LKMES2.MES_MME_MEASURE_SITE.SITE_TYPE
	 * 
	 * @ibatorgenerated Sat Oct 12 16:56:56 CST 2013
	 */
	public void setSiteType(String siteType) {
		this.siteType = siteType;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column LKMES2.MES_MME_MEASURE_SITE.ZERO_STANDARD
	 * 
	 * @return the value of LKMES2.MES_MME_MEASURE_SITE.ZERO_STANDARD
	 * 
	 * @ibatorgenerated Sat Oct 12 16:56:56 CST 2013
	 */
	public String getZeroStandard() {
		return zeroStandard;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column LKMES2.MES_MME_MEASURE_SITE.ZERO_STANDARD
	 * 
	 * @param zeroStandard
	 *          the value for LKMES2.MES_MME_MEASURE_SITE.ZERO_STANDARD
	 * 
	 * @ibatorgenerated Sat Oct 12 16:56:56 CST 2013
	 */
	public void setZeroStandard(String zeroStandard) {
		this.zeroStandard = zeroStandard;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column LKMES2.MES_MME_MEASURE_SITE.COM_PORT
	 * 
	 * @return the value of LKMES2.MES_MME_MEASURE_SITE.COM_PORT
	 * 
	 * @ibatorgenerated Sat Oct 12 16:56:56 CST 2013
	 */
	public String getComPort() {
		return comPort;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column LKMES2.MES_MME_MEASURE_SITE.COM_PORT
	 * 
	 * @param comPort
	 *          the value for LKMES2.MES_MME_MEASURE_SITE.COM_PORT
	 * 
	 * @ibatorgenerated Sat Oct 12 16:56:56 CST 2013
	 */
	public void setComPort(String comPort) {
		this.comPort = comPort;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column LKMES2.MES_MME_MEASURE_SITE.COM_FREQUENCY
	 * 
	 * @return the value of LKMES2.MES_MME_MEASURE_SITE.COM_FREQUENCY
	 * 
	 * @ibatorgenerated Sat Oct 12 16:56:56 CST 2013
	 */
	public Integer getComFrequency() {
		return comFrequency;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column LKMES2.MES_MME_MEASURE_SITE.COM_FREQUENCY
	 * 
	 * @param comFrequency
	 *          the value for LKMES2.MES_MME_MEASURE_SITE.COM_FREQUENCY
	 * 
	 * @ibatorgenerated Sat Oct 12 16:56:56 CST 2013
	 */
	public void setComFrequency(Integer comFrequency) {
		this.comFrequency = comFrequency;
	}

	public Long getSid() {
		return sid;
	}

	public void setSid(Long sid) {
		this.sid = sid;
	}

}